export type Condition = 'Normal'|'Low RAM'|'Low Battery'|'Offline';
export type Mode = 'CLOUD'|'LOCAL'|'LOGIC'|'ANDROID'|'INPUT';
export type Step = { id:string; name:string; input:string; output:string; capability?:string; min:number; kind?:'trigger'|'logic'|'android' };
export type Flow = { id:string; title:string; domain:string; description:string; prompt:string; steps:Step[]; eta:string };
export const flows:Flow[] = [
 {id:'expense',title:'Smart Expense',domain:'FINANCE',description:'Handwritten bill → categorized expense',prompt:'Take a photo of my handwritten bill, extract the items and prices, calculate the total, categorize the expenses and add them to my expense tracker.',eta:'12 sec',steps:[{id:'capture',name:'Capture bill',input:'Bill image',output:'Image ready',min:0,kind:'android'},{id:'read',name:'Read bill',input:'Handwritten bill image',output:'Items + prices',capability:'vision + OCR',min:90},{id:'total',name:'Calculate total',input:'Extracted line items',output:'₹1,248.50',min:0,kind:'logic'},{id:'categorize',name:'Categorize expenses',input:'Items + merchant',output:'3 categories',capability:'text',min:85},{id:'add',name:'Add to Expense Tracker',input:'Total + categories',output:'Pending confirmation',min:0,kind:'android'}]},
 {id:'study',title:'Study Pack',domain:'EDUCATION',description:'Lecture audio → notes + quiz',prompt:'Take this lecture recording, transcribe it, identify important concepts, create study notes and generate five quiz questions.',eta:'18 sec',steps:[{id:'audio',name:'Lecture audio',input:'Sample lecture recording',output:'Audio waveform',min:0,kind:'trigger'},{id:'transcribe',name:'Transcribe lecture',input:'Lecture audio',output:'Transcript',capability:'stt',min:85},{id:'concepts',name:'Identify key concepts',input:'Transcript',output:'5 concepts',capability:'text',min:75},{id:'notes',name:'Summary + study notes',input:'Transcript + concepts',output:'Study notes',capability:'text',min:90},{id:'quiz',name:'Generate 5 quiz questions',input:'Study notes',output:'5 questions',capability:'text',min:90}]},
 {id:'plant',title:'Plant Analysis',domain:'VISUAL ANALYSIS',description:'Leaf photo → careful plant care plan',prompt:'Analyze this plant leaf and suggest a care plan.',eta:'14 sec',steps:[{id:'photo',name:'Plant image',input:'Leaf photo',output:'Image ready',min:0,kind:'trigger'},{id:'quality',name:'Image quality check',input:'Leaf photo',output:'Image quality OK',min:0,kind:'logic'},{id:'assess',name:'Assess leaf condition',input:'Leaf image',output:'Model assessment',capability:'vision',min:90},{id:'symptoms',name:'Symptoms + explanation',input:'Assessment',output:'Possible issue',capability:'text',min:90},{id:'care',name:'Recommended care plan',input:'Assessment + symptoms',output:'Next steps',capability:'text',min:90}]},
 {id:'meeting',title:'Meeting Notes',domain:'PRODUCTIVITY',description:'Meeting recording → concise notes',prompt:'Summarize my meeting recording into action items.',eta:'Preview',steps:[{id:'m1',name:'Meeting audio',input:'Audio file',output:'Audio ready',min:0},{id:'m2',name:'Transcribe + extract actions',input:'Meeting audio',output:'Action items',capability:'stt',min:80}]},
 {id:'document',title:'Document Analyzer',domain:'HEALTHCARE',description:'Document → structured summary',prompt:'Summarize this PDF document.',eta:'Preview',steps:[{id:'d1',name:'Read document',input:'PDF',output:'Extracted text',capability:'ocr',min:80},{id:'d2',name:'Create structured summary',input:'Document text',output:'Summary',capability:'text',min:85}]},
 {id:'accessibility',title:'Voice In / Out',domain:'ACCESSIBILITY',description:'Voice input → spoken response',prompt:'Read this information aloud in simple language.',eta:'Preview',steps:[{id:'a1',name:'Understand request',input:'Voice or text',output:'Intent',capability:'stt',min:80},{id:'a2',name:'Speak response',input:'Simple answer',output:'Audio',capability:'text',min:80}]}
];
export const models=[{id:'gemini-flash',name:'Gemini 3.8 Flash',mode:'CLOUD',cap:['vision','ocr','text','classify_image'],ram:0,disk:0,battery:'Low',latency:420,accuracy:94},{id:'gemini-transcribe',name:'Gemini 3.5 Transcribe',mode:'CLOUD',cap:['stt'],ram:0,disk:0,battery:'Low',latency:900,accuracy:96},{id:'local-vision',name:'Local Vision Model',mode:'LOCAL',cap:['vision','ocr'],ram:2.7,disk:2800,battery:'Medium',latency:680,accuracy:88},{id:'local-vision-lite',name:'Local Vision Lite',mode:'LOCAL',cap:['vision','ocr'],ram:1.8,disk:1400,battery:'Medium',latency:900,accuracy:79},{id:'ocr-engine',name:'OCR Engine',mode:'LOCAL',cap:['ocr'],ram:.3,disk:120,battery:'Low',latency:180,accuracy:84},{id:'local-stt',name:'Local Speech-to-Text',mode:'LOCAL',cap:['stt'],ram:.8,disk:780,battery:'Medium',latency:1100,accuracy:88},{id:'local-llm-lite',name:'Local Lightweight LLM',mode:'LOCAL',cap:['text'],ram:.9,disk:900,battery:'Medium',latency:350,accuracy:82},{id:'image-classifier',name:'Image Classifier',mode:'LOCAL',cap:['classify_image','vision'],ram:.4,disk:24,battery:'Low',latency:150,accuracy:85},{id:'embedding-mini',name:'Embedding Model',mode:'LOCAL',cap:['embed'],ram:.2,disk:90,battery:'Low',latency:40,accuracy:0}];
export function routeStep(step:Step,condition:Condition){if(step.kind==='trigger')return {model:'Input Trigger',mode:'INPUT' as Mode,score:100,reason:'User supplied input; no model execution is needed.'};if(step.kind==='logic')return {model:'Local Logic',mode:'LOGIC' as Mode,score:100,reason:'Deterministic operation; no AI model needed.'};if(step.kind==='android')return {model:'Android Action',mode:'ANDROID' as Mode,score:100,reason:'Runs through a user-confirmed Android action.'};const usable=condition==='Low RAM'?0:2.2;const battery=condition==='Low Battery';const needs=(step.capability||'').toLowerCase().split('+').map(c=>c.trim()).filter(Boolean);const candidates=models.filter(m=>needs.every(c=>m.cap.includes(c))).filter(m=>m.mode==='CLOUD'?condition!=='Offline':m.ram<=usable&&!(battery&&m.battery==='Medium'));
 const score=(m:typeof models[number])=>Math.round((m.accuracy*.4+(1-Math.min(m.latency,2000)/2000)*25+(m.battery==='Low'?19:m.battery==='Medium'?12:5)+(1-Math.min(m.disk,3000)/3000)*15));
 const local=candidates.filter(m=>m.mode==='LOCAL'&&m.accuracy>=step.min).sort((a,b)=>score(b)-score(a))[0];const cloud=candidates.filter(m=>m.mode==='CLOUD').sort((a,b)=>score(b)-score(a))[0];const chosen=local??cloud??candidates.filter(m=>m.mode==='LOCAL').sort((a,b)=>score(b)-score(a))[0];if(!chosen)return {model:'Ask user',mode:'LOCAL' as Mode,score:0,reason:'No compatible model is available.'};return {model:chosen.name,mode:chosen.mode as Mode,score:score(chosen),reason:chosen.mode==='CLOUD'?'Cloud model meets the accuracy target; local options do not fit the available resources.':chosen.accuracy<step.min?'Cloud unavailable; local fallback selected with reduced accuracy.':'Best-scoring local model that meets the accuracy target.'};}
